/**
 * 人気ランキング(ranking.html)用の上位50件(自動生成ファイル。手編集しないこと)。
 * generate-list-data.js が data-playlists.js から ranking.js の computeRankingList() で生成する。
 */
const RANKING_LIST = {
 "version": 1,
 "items": [
  {
   "id": "niji-eluworld-35",
   "title": "APEX",
   "streamer": "える",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PLlKNHmvM5HaDMrL9Sw6leAojcpVW4laDa",
   "thumbnailUrl": "https://i.ytimg.com/vi/UhFs645qxXE/mqdefault.jpg",
   "videoCount": 1036,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-09-24",
   "_rank": 1
  },
  {
   "id": "niji-sakuraritsuk-27",
   "title": "マイクラ",
   "streamer": "桜凛月",
   "game": "Minecraft",
   "genre": "sandbox",
   "playlistId": "PLocKfGhRosWTZ7nv3ozx8tyWfaVldXc9N",
   "thumbnailUrl": "https://i.ytimg.com/vi/rz28BeiEuTc/mqdefault.jpg",
   "videoCount": 793,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-09-22",
   "_rank": 2
  },
  {
   "id": "niji-kanae2434-37",
   "title": "Apex Legends",
   "streamer": "叶",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PLXKMRoeWMiAlKk-PsLQ4xnkeRSA8lcupG",
   "thumbnailUrl": "https://i.ytimg.com/vi/tNjSQb-twJ0/mqdefault.jpg",
   "videoCount": 657,
   "addedDate": "2026-09-08",
   "updatedDate": "2023-08-23",
   "_rank": 3
  },
  {
   "id": "niji-seffyna2434-12",
   "title": "🧱Minecraft",
   "streamer": "セフィナ",
   "game": "Minecraft",
   "genre": "sandbox",
   "playlistId": "PLVkryDuTSzpNSJg88R_P_9B5azNoS85zR",
   "thumbnailUrl": "https://i.ytimg.com/vi/fi_8JLjdQb8/mqdefault.jpg",
   "videoCount": 494,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-09-21",
   "_rank": 4
  },
  {
   "id": "vspo-yuuhisendo-36",
   "title": "League of Legends",
   "streamer": "千燈ゆうひ",
   "game": "League of Legends",
   "genre": "other",
   "playlistId": "PL7rBIMrt1ue5OQr1HncWbkvhepX-6_bIr",
   "thumbnailUrl": "https://i.ytimg.com/vi/MgopQQWE05o/mqdefault.jpg",
   "videoCount": 414,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-06",
   "_rank": 5
  },
  {
   "id": "niji-belmondb2434-59",
   "title": "マイクラ",
   "streamer": "ベルモンド・バンデラス",
   "game": "Minecraft",
   "genre": "sandbox",
   "playlistId": "PLwpJFw_gqGL_LY3huaBE_MbZZ4ONgDCHs",
   "thumbnailUrl": "https://i.ytimg.com/vi/A5uMHwNNc28/mqdefault.jpg",
   "videoCount": 402,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-08-15",
   "_rank": 6
  },
  {
   "id": "vspo-hinanotachib-39",
   "title": "コラボAPEX",
   "streamer": "橘ひなの",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PLzzYMrfmt7TCwfFQf7XRLES6B3HGXOFUa",
   "thumbnailUrl": "https://i.ytimg.com/vi/28AnsNui9Nw/mqdefault.jpg",
   "videoCount": 391,
   "addedDate": "2026-09-07",
   "updatedDate": "2025-08-17",
   "_rank": 7
  },
  {
   "id": "niji-sukosukosuko-06",
   "title": "ストグラ",
   "streamer": "健屋花那",
   "game": "Grand Theft Auto V",
   "genre": "action",
   "playlistId": "PL0SNK9gKZgKu3hETMrIDJJijAaQpozZV9",
   "thumbnailUrl": "https://i.ytimg.com/vi/zB2h7kUTFTY/mqdefault.jpg",
   "videoCount": 387,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-08-29",
   "_rank": 8
  },
  {
   "id": "vspo-beniyakumo-26",
   "title": "Valorant",
   "streamer": "八雲べに",
   "game": "VALORANT",
   "genre": "fps",
   "playlistId": "PLcIUhxw5ceRB5XoaAm877bFxlSQjCPG62",
   "thumbnailUrl": "https://i.ytimg.com/vi/he9BvDzasLA/mqdefault.jpg",
   "videoCount": 359,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-08-30",
   "_rank": 9
  },
  {
   "id": "vspo-lisahanabusa-11",
   "title": "APEX",
   "streamer": "英リサ",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PLMbPsuw36kCglBhUr2Vx_mh_wv7QWl6j2",
   "thumbnailUrl": "https://i.ytimg.com/vi/VpDqGHG17GU/mqdefault.jpg",
   "videoCount": 351,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-26",
   "_rank": 10
  },
  {
   "id": "vspo-lisahanabusa-06",
   "title": "VALORANT",
   "streamer": "英リサ",
   "game": "VALORANT",
   "genre": "fps",
   "playlistId": "PLMbPsuw36kChBG5HS1cSNb_zpK8JX9Ht_",
   "thumbnailUrl": "https://i.ytimg.com/vi/7xClVATmdQM/mqdefault.jpg",
   "videoCount": 348,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-25",
   "_rank": 11
  },
  {
   "id": "vspo-kokagetsumug-13",
   "title": "VALORANT",
   "streamer": "紡木こかげ",
   "game": "VALORANT",
   "genre": "fps",
   "playlistId": "PLsYH4NvRwnM2cqKLaoZ4mt5s6hSchl5WR",
   "thumbnailUrl": "https://i.ytimg.com/vi/YStlXqyJVYQ/mqdefault.jpg",
   "videoCount": 347,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-23",
   "_rank": 12
  },
  {
   "id": "vspo-senaasumi-22",
   "title": "APEX",
   "streamer": "空澄セナ",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PL3DQu__wv2WC9J3t_5xUZYATYLX5HWVSB",
   "thumbnailUrl": "https://i.ytimg.com/vi/RlFS8DP8XxI/mqdefault.jpg",
   "videoCount": 342,
   "addedDate": "2026-09-07",
   "updatedDate": "2024-09-23",
   "_rank": 13
  },
  {
   "id": "vspo-tsunanekota-29",
   "title": "VALORANT",
   "streamer": "猫汰つな",
   "game": "VALORANT",
   "genre": "fps",
   "playlistId": "PLAu9d4ZNkEX4jJFf4wy9t5GLMMhjRiA5Q",
   "thumbnailUrl": "https://i.ytimg.com/vi/K0WXMm_Ai_M/mqdefault.jpg",
   "videoCount": 337,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-20",
   "_rank": 14
  },
  {
   "id": "niji-kanae2434-07",
   "title": "ストグラ〚 無馬かな 〛",
   "streamer": "叶",
   "game": "Grand Theft Auto V",
   "genre": "action",
   "playlistId": "PLXKMRoeWMiAlWoLdsh0K_Lhlv2I7D8vyP",
   "thumbnailUrl": "https://i.ytimg.com/vi/6dmPIUpB3ys/mqdefault.jpg",
   "videoCount": 333,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-07-28",
   "_rank": 15
  },
  {
   "id": "niji-ratnapetit-30",
   "title": "APEX",
   "streamer": "ラトナ・プティ",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PLO0S4-ytGe7-_53RaOpmk-B70W229IKp1",
   "thumbnailUrl": "https://i.ytimg.com/vi/R0iDP3sBoSw/mqdefault.jpg",
   "videoCount": 331,
   "addedDate": "2026-09-08",
   "updatedDate": "2024-09-15",
   "_rank": 16
  },
  {
   "id": "vspo-amayuimoka-09",
   "title": "ストリートファイター６！",
   "streamer": "甘結もか",
   "game": "ストリートファイター6",
   "genre": "action",
   "playlistId": "PLCfMG0B3GdeaRcBL8ok3CcAAgEXphXAmG",
   "thumbnailUrl": "https://i.ytimg.com/vi/7uO5y3pyiS8/mqdefault.jpg",
   "videoCount": 288,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-25",
   "_rank": 17
  },
  {
   "id": "holo-074",
   "title": "マインクラフト🐏",
   "streamer": "角巻わため",
   "game": "Minecraft",
   "genre": "sandbox",
   "playlistId": "PLZ34fLWik_iBPCTi4beXGLxeMYKQZRTqd",
   "thumbnailUrl": "https://i.ytimg.com/vi/PwINloYDiv4/mqdefault.jpg",
   "videoCount": 279,
   "addedDate": "2026-09-06",
   "updatedDate": "2026-09-26",
   "_rank": 18
  },
  {
   "id": "vspo-mimitosaki-04",
   "title": "VALORANT",
   "streamer": "兎咲ミミ",
   "game": "VALORANT",
   "genre": "fps",
   "playlistId": "PLrZeo6egs0S4A7TRW_2tnb3P_1HIUPneB",
   "thumbnailUrl": "https://i.ytimg.com/vi/288wCC5EPpU/mqdefault.jpg",
   "videoCount": 279,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-24",
   "_rank": 19
  },
  {
   "id": "nijien-ryomabarrenwort-01",
   "title": "Apex Legends",
   "streamer": "Ryoma Barrenwort",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PLieuRaHLhA2-SoDhe2YpsfcXGnnnlwwqi",
   "thumbnailUrl": "https://i.ytimg.com/vi/B2NboYPr96Y/mqdefault.jpg",
   "videoCount": 272,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-09-25",
   "_rank": 20
  },
  {
   "id": "vspo-tsunanekota-32",
   "title": "APEX",
   "streamer": "猫汰つな",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PLAu9d4ZNkEX52vmwihd9CGubDazFNgbKv",
   "thumbnailUrl": "https://i.ytimg.com/vi/mMYdlv-D2hc/mqdefault.jpg",
   "videoCount": 264,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-25",
   "_rank": 21
  },
  {
   "id": "holo-059",
   "title": "Minecraft",
   "streamer": "不知火フレア",
   "game": "Minecraft",
   "genre": "sandbox",
   "playlistId": "PLBoFNGFmekcNR8kWdLUFPHoagiuUDmdch",
   "thumbnailUrl": "https://i.ytimg.com/vi/EdrSjHMQOHk/mqdefault.jpg",
   "videoCount": 263,
   "addedDate": "2026-09-06",
   "updatedDate": "2026-09-24",
   "_rank": 22
  },
  {
   "id": "niji-higuchikaede-27",
   "title": "APEX",
   "streamer": "樋口楓",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PLXVn5n2jQV_ADOooJWtCXN_c_Uogl1p8A",
   "thumbnailUrl": "https://i.ytimg.com/vi/Z-fvQmwnsK0/mqdefault.jpg",
   "videoCount": 251,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-09-25",
   "_rank": 23
  },
  {
   "id": "niji-sarahoshikaw-18",
   "title": "🌟APEX配信",
   "streamer": "星川サラ",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PLubTcmKzPseTjMIVPWYLRFfC60S1zUf6X",
   "thumbnailUrl": "https://i.ytimg.com/vi/en1w8pCy53Y/mqdefault.jpg",
   "videoCount": 246,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-01-22",
   "_rank": 24
  },
  {
   "id": "vspo-totokogara-08",
   "title": "チームタルコフ",
   "streamer": "小雀とと",
   "game": "Escape from Tarkov",
   "genre": "fps",
   "playlistId": "PLuXZStCIRGE3W7JVT7FRbe7JG1lxAziIW",
   "thumbnailUrl": "https://i.ytimg.com/vi/84Rzt5_YwtA/mqdefault.jpg",
   "videoCount": 239,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-25",
   "_rank": 25
  },
  {
   "id": "niji-hayun2434-01",
   "title": "APEX",
   "streamer": "ハ ユン",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PLxd6nfPnUZE2lpQ3eTum_C0tVu79Wj6BA",
   "thumbnailUrl": "https://i.ytimg.com/vi/DeBhR07T6dA/mqdefault.jpg",
   "videoCount": 239,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-06-23",
   "_rank": 26
  },
  {
   "id": "holoid-kureijiollie-01",
   "title": "APEX",
   "streamer": "Kureiji Ollie",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PL6DI34hJswwRAtXhOBtrgt86erzpqNRiO",
   "thumbnailUrl": "https://i.ytimg.com/vi/XZj05IVJK_8/mqdefault.jpg",
   "videoCount": 235,
   "addedDate": "2026-09-08",
   "updatedDate": "2024-03-09",
   "_rank": 27
  },
  {
   "id": "niji-kirame2434-27",
   "title": "雀魂🀄✨",
   "streamer": "空星きらめ",
   "game": "雀魂",
   "genre": "other",
   "playlistId": "PLcEj_AhpEQ3nQ7ETwU85spL0wJlhaNBDa",
   "thumbnailUrl": "https://i.ytimg.com/vi/rLu4zEvad4Q/mqdefault.jpg",
   "videoCount": 225,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-09-16",
   "_rank": 28
  },
  {
   "id": "niji-597",
   "title": "アークナイツ",
   "streamer": "ドーラ",
   "game": "アークナイツ",
   "genre": "sim",
   "playlistId": "PLjrPrY0wwbW_xCVo9f7Zo6weagxCRQrCu",
   "thumbnailUrl": "https://i.ytimg.com/vi/b3Lhc4yHYoc/mqdefault.jpg",
   "videoCount": 216,
   "addedDate": "2026-09-06",
   "updatedDate": "2026-06-29",
   "_rank": 29
  },
  {
   "id": "niji-shizurin23-41",
   "title": "凛LIVE --- FF14 (配信全て)",
   "streamer": "静凛",
   "game": "FINAL FANTASY XIV",
   "genre": "rpg",
   "playlistId": "PL0EE7SG9o_r9jWx7TQJ7rhRW7HFa-KH4G",
   "thumbnailUrl": "https://i.ytimg.com/vi/zpkuuTzBNmo/mqdefault.jpg",
   "videoCount": 210,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-09-08",
   "_rank": 30
  },
  {
   "id": "vspo-hanabichoya-20",
   "title": "︎︎⟡スト６︎︎⟡",
   "streamer": "蝶屋はなび",
   "game": "ストリートファイター6",
   "genre": "action",
   "playlistId": "PLku7p0RAD_ysOCNWBElvNEw5396XSS5fw",
   "thumbnailUrl": "https://i.ytimg.com/vi/sppiv-cbDXQ/mqdefault.jpg",
   "videoCount": 208,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-24",
   "_rank": 31
  },
  {
   "id": "holo-001",
   "title": "マインクラフト",
   "streamer": "ときのそら",
   "game": "Minecraft",
   "genre": "sandbox",
   "playlistId": "PL_0A0t0-Y0APTOx_tishwxC32q_BQdYc0",
   "thumbnailUrl": "https://i.ytimg.com/vi/yNHUQortMv0/mqdefault.jpg",
   "videoCount": 207,
   "addedDate": "2026-09-06",
   "updatedDate": "2026-06-05",
   "_rank": 32
  },
  {
   "id": "niji-fuwaminato-22",
   "title": "APEX",
   "streamer": "不破湊",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PL2uMwjy4y2Z5e1h9vOaerBvXEQ3hWnvhY",
   "thumbnailUrl": "https://i.ytimg.com/vi/XF2FkOWJDHE/mqdefault.jpg",
   "videoCount": 205,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-09-26",
   "_rank": 33
  },
  {
   "id": "niji-shizurin23-28",
   "title": "凛LIVE --- FF14 (et cetera/NOPLAN)",
   "streamer": "静凛",
   "game": "FINAL FANTASY XIV",
   "genre": "rpg",
   "playlistId": "PL0EE7SG9o_r9qGeF-U2cWL92s-yOHua2r",
   "thumbnailUrl": "https://i.ytimg.com/vi/ge6bLecsFVc/mqdefault.jpg",
   "videoCount": 201,
   "addedDate": "2026-09-08",
   "updatedDate": "2024-10-27",
   "_rank": 34
  },
  {
   "id": "niji-459",
   "title": "スプラトゥーン",
   "streamer": "不破湊",
   "game": "スプラトゥーン",
   "genre": "fps",
   "playlistId": "PL2uMwjy4y2Z72nrj-xwUAlnz-mwZ_Oqoz",
   "thumbnailUrl": "https://i.ytimg.com/vi/D3FSZ8MAyQg/mqdefault.jpg",
   "videoCount": 199,
   "addedDate": "2026-09-06",
   "updatedDate": "2026-01-30",
   "_rank": 35
  },
  {
   "id": "niji-chigusa24zon-13",
   "title": "⟡ 原神",
   "streamer": "西園チグサ",
   "game": "原神",
   "genre": "rpg",
   "playlistId": "PLYqQxMpsjrWsACCzSgFfJJG-T1BKbuuMl",
   "thumbnailUrl": "https://i.ytimg.com/vi/AtXswQOokxQ/mqdefault.jpg",
   "videoCount": 199,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-09-20",
   "_rank": 36
  },
  {
   "id": "niji-nuisociere-41",
   "title": "🥕ウマ娘プリティダービー🥕",
   "streamer": "ニュイ・ソシエール",
   "game": "ウマ娘 プリティーダービー",
   "genre": "sim",
   "playlistId": "PLCkTosaqp5q1LuMrzHMEmkA_B2K1sjVBZ",
   "thumbnailUrl": "https://i.ytimg.com/vi/sM-ej41LYNA/mqdefault.jpg",
   "videoCount": 196,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-09-20",
   "_rank": 37
  },
  {
   "id": "vspo-ramuneshiran-13",
   "title": "VALORANT",
   "streamer": "白波らむね",
   "game": "VALORANT",
   "genre": "fps",
   "playlistId": "PLUdUwPsjjzfGNmKkZBcuCLGIKz6G4g9FL",
   "thumbnailUrl": "https://i.ytimg.com/vi/pHFCpzwxF_E/mqdefault.jpg",
   "videoCount": 193,
   "addedDate": "2026-09-07",
   "updatedDate": "2024-03-25",
   "_rank": 38
  },
  {
   "id": "vspo-beniyakumo-25",
   "title": "APEX",
   "streamer": "八雲べに",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PLcIUhxw5ceRDRhZNUiz4XWvsLN-ufcs3q",
   "thumbnailUrl": "https://i.ytimg.com/vi/wbwaiLeTrsY/mqdefault.jpg",
   "videoCount": 188,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-26",
   "_rank": 39
  },
  {
   "id": "vspo-emaaizawa-10",
   "title": "スト6",
   "streamer": "藍沢エマ",
   "game": "ストリートファイター6",
   "genre": "action",
   "playlistId": "PLyqh3naVl78Gi4C504n43RNBJGjdx1lP9",
   "thumbnailUrl": "https://i.ytimg.com/vi/2m9N5_KnRDE/mqdefault.jpg",
   "videoCount": 188,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-24",
   "_rank": 40
  },
  {
   "id": "niji-yuuhiriri-49",
   "title": "未来人のDead by Daylight",
   "streamer": "夕陽リリ",
   "game": "Dead by Daylight",
   "genre": "horror",
   "playlistId": "PLuru-CHwNWA5aBCwLBC3mulqrHcbnS6GM",
   "thumbnailUrl": "https://i.ytimg.com/vi/46VOgRfQOQg/mqdefault.jpg",
   "videoCount": 188,
   "addedDate": "2026-09-08",
   "updatedDate": "2025-09-20",
   "_rank": 41
  },
  {
   "id": "vspo-emaaizawa-05",
   "title": "Apex Legends",
   "streamer": "藍沢エマ",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PLHxtjnqjYjiI",
   "thumbnailUrl": "https://i.ytimg.com/vi/bCnRk6HMoEw/mqdefault.jpg",
   "videoCount": 187,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-25",
   "_rank": 42
  },
  {
   "id": "niji-toru2434-57",
   "title": "Minecraft",
   "streamer": "小清水透",
   "game": "Minecraft",
   "genre": "sandbox",
   "playlistId": "PL9mzRTKsqnF6bZ4v_FGLMMIP8B5ETPMCV",
   "thumbnailUrl": "https://i.ytimg.com/vi/c7QvWCtQWPw/mqdefault.jpg",
   "videoCount": 187,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-07-29",
   "_rank": 43
  },
  {
   "id": "vspo-mimitosaki-09",
   "title": "APEX",
   "streamer": "兎咲ミミ",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PLrZeo6egs0S58nURtU_2if7FkTYlrEaD1",
   "thumbnailUrl": "https://i.ytimg.com/vi/hGqHSYZ3-Bw/mqdefault.jpg",
   "videoCount": 186,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-22",
   "_rank": 44
  },
  {
   "id": "niji-tr0ut2434-02",
   "title": "マインクラフト全て",
   "streamer": "渚トラウト",
   "game": "Minecraft",
   "genre": "sandbox",
   "playlistId": "PL8_jKJuJUx8o9pxZG8sEuHCrfybT4P_ZE",
   "thumbnailUrl": "https://i.ytimg.com/vi/_IBTOKVI030/mqdefault.jpg",
   "videoCount": 180,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-09-18",
   "_rank": 45
  },
  {
   "id": "vspo-hinanotachib-42",
   "title": "APEX",
   "streamer": "橘ひなの",
   "game": "Apex Legends",
   "genre": "fps",
   "playlistId": "PLzzYMrfmt7TAn5WuFJVUaSLmftM31Pxsh",
   "thumbnailUrl": "https://i.ytimg.com/vi/WnOccP557mQ/mqdefault.jpg",
   "videoCount": 178,
   "addedDate": "2026-09-07",
   "updatedDate": "2026-09-25",
   "_rank": 46
  },
  {
   "id": "niji-429",
   "title": "スプラトゥーン２",
   "streamer": "健屋花那",
   "game": "スプラトゥーン2",
   "genre": "fps",
   "playlistId": "PL0SNK9gKZgKs5gIWci_K3nYV7BW27IgWy",
   "thumbnailUrl": "https://i.ytimg.com/vi/dHdby0oO0Dw/mqdefault.jpg",
   "videoCount": 177,
   "addedDate": "2026-09-06",
   "updatedDate": "2026-06-10",
   "_rank": 47
  },
  {
   "id": "niji-kurusu72me-14",
   "title": "MINECRAFT",
   "streamer": "来栖夏芽",
   "game": "Minecraft",
   "genre": "sandbox",
   "playlistId": "PLIM2FRyoN8cqOOHa4r8bdqnwNiHJEo1eo",
   "thumbnailUrl": "https://i.ytimg.com/vi/2I1PBlyhxZE/mqdefault_live.jpg",
   "videoCount": 175,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-09-05",
   "_rank": 48
  },
  {
   "id": "vspo-nazunakaga-11",
   "title": "PUBGアーカイブ",
   "streamer": "花芽なずな",
   "game": "PUBG: BATTLEGROUNDS",
   "genre": "fps",
   "playlistId": "PL_tHdrZUlaGnP1e_KzVZ1X26H_W8rSHHo",
   "thumbnailUrl": "https://i.ytimg.com/vi/OaMMzbO2G5M/mqdefault.jpg",
   "videoCount": 174,
   "addedDate": "2026-09-07",
   "updatedDate": "2020-09-09",
   "_rank": 49
  },
  {
   "id": "niji-amamiyakokor-42",
   "title": "✧雀魂 / 麻雀 │ 天宮こころ",
   "streamer": "天宮こころ",
   "game": "雀魂",
   "genre": "other",
   "playlistId": "PLf_iCnxqBv4iXKd3wOEXOS7xyZ5EsDY73",
   "thumbnailUrl": "https://i.ytimg.com/vi/D-hXsv1Wv88/mqdefault.jpg",
   "videoCount": 166,
   "addedDate": "2026-09-08",
   "updatedDate": "2026-08-11",
   "_rank": 50
  }
 ]
};
