/**
 * 新着再生リスト(new.html)用の50件(自動生成ファイル。手編集しないこと)。
 * generate-list-data.js が data-playlists.js から new.js の computeNewList() で生成する。
 */
const NEW_LIST = {
 "version": 1,
 "items": [
  {
   "id": "gap797",
   "title": "✧桃太郎電鉄 │ 天宮こころ",
   "streamer": "天宮こころ",
   "game": "桃太郎電鉄",
   "genre": "other",
   "playlistId": "PLf_iCnxqBv4j6VasTg02T9Ch4k7WmMXVH",
   "thumbnailUrl": "https://i.ytimg.com/vi/yqpsIVhQeqQ/mqdefault.jpg",
   "videoCount": 5,
   "addedDate": "2026-09-19",
   "updatedDate": "2026-05-05"
  },
  {
   "id": "gap786",
   "title": "〖マリオテニス フィーバー〗",
   "streamer": "笹木咲",
   "game": "マリオテニス",
   "genre": "sports",
   "playlistId": "PLed6q99qvCSdMtV7ReiVvTd8xyGVvH32G",
   "thumbnailUrl": "https://i.ytimg.com/vi/xq0NPzK-Lvk/mqdefault.jpg",
   "videoCount": 5,
   "addedDate": "2026-09-19",
   "updatedDate": "2026-02-24"
  },
  {
   "id": "gap812",
   "title": "METAL GEAR SOLID Δ: SNAKE EATER",
   "streamer": "Freodore",
   "game": "METAL GEAR SOLID Δ: SNAKE EATER",
   "genre": "action",
   "playlistId": "PLiYIbLbIkhBg8qOrQlDHLfkF3daKpwq7u",
   "thumbnailUrl": "https://i.ytimg.com/vi/gb42khqzlOw/mqdefault.jpg",
   "videoCount": 4,
   "addedDate": "2026-09-19",
   "updatedDate": "2025-09-25"
  },
  {
   "id": "gap818",
   "title": "【MGS】【メタルギア ソリッド デルタ: スネークイーター】",
   "streamer": "葛葉",
   "game": "METAL GEAR SOLID Δ: SNAKE EATER",
   "genre": "action",
   "playlistId": "PLwCa-x--ILnZRaOJjnLazr7j46KuKR2Vf",
   "thumbnailUrl": "https://i.ytimg.com/vi/ORA9bhScu3c/mqdefault.jpg",
   "videoCount": 3,
   "addedDate": "2026-09-19",
   "updatedDate": "2025-09-04"
  },
  {
   "id": "gap811",
   "title": "MGSΔ",
   "streamer": "ベルモンド・バンデラス",
   "game": "METAL GEAR SOLID Δ: SNAKE EATER",
   "genre": "action",
   "playlistId": "PLwpJFw_gqGL9nVt87KRrTzwIxGasZnKBn",
   "thumbnailUrl": "https://i.ytimg.com/vi/FWE5H79Bj_4/mqdefault.jpg",
   "videoCount": 5,
   "addedDate": "2026-09-19",
   "updatedDate": "2025-09-03"
  },
  {
   "id": "gap787",
   "title": "凛LIVE --- R.E.P.O.",
   "streamer": "静凛",
   "game": "R.E.P.O.",
   "genre": "horror",
   "playlistId": "PL0EE7SG9o_r9j9fmgjtbA7Pe6Nv3S_9TG",
   "thumbnailUrl": "https://i.ytimg.com/vi/40TcCBOlnw0/mqdefault.jpg",
   "videoCount": 13,
   "addedDate": "2026-09-19",
   "updatedDate": "2025-08-16"
  },
  {
   "id": "gap810",
   "title": "キャラバンハート　ドラクエモンスターズ",
   "streamer": "ベルモンド・バンデラス",
   "game": "ドラゴンクエストモンスターズ キャラバンハート",
   "genre": "rpg",
   "playlistId": "PLwpJFw_gqGL_zi-V_V9j4ADWJpSeHO__k",
   "thumbnailUrl": "https://i.ytimg.com/vi/ablvtsfUrEg/mqdefault.jpg",
   "videoCount": 6,
   "addedDate": "2026-09-19",
   "updatedDate": "2025-06-26"
  },
  {
   "id": "gap808",
   "title": "モンハン：ワイルズ",
   "streamer": "小清水透",
   "game": "モンスターハンターワイルズ",
   "genre": "action",
   "playlistId": "PL9mzRTKsqnF5X_KplVlOcgVHNHZXGDXMu",
   "thumbnailUrl": "https://i.ytimg.com/vi/wRiN0_SiayU/mqdefault.jpg",
   "videoCount": 5,
   "addedDate": "2026-09-19",
   "updatedDate": "2025-05-29"
  },
  {
   "id": "gap788",
   "title": "凛 --- ゲーム発展国++",
   "streamer": "静凛",
   "game": "ゲーム発展国++",
   "genre": "sim",
   "playlistId": "PL0EE7SG9o_r_oaicpFI8RppxGcVUq0WVR",
   "thumbnailUrl": "https://i.ytimg.com/vi/XVTMEaHgeng/mqdefault.jpg",
   "videoCount": 2,
   "addedDate": "2026-09-19",
   "updatedDate": "2025-05-22"
  },
  {
   "id": "gap805",
   "title": "ドラクエモンスターズRETRO",
   "streamer": "ベルモンド・バンデラス",
   "game": "ドラゴンクエストモンスターズ テリーのワンダーランドRETRO",
   "genre": "rpg",
   "playlistId": "PLwpJFw_gqGL8QyqVffaD6aAKgcJC1Gmi9",
   "thumbnailUrl": "https://i.ytimg.com/vi/Td4syy47Cv4/mqdefault.jpg",
   "videoCount": 8,
   "addedDate": "2026-09-19",
   "updatedDate": "2025-05-10"
  },
  {
   "id": "gap813",
   "title": "第一回ストリーマーRUST",
   "streamer": "イブラヒム",
   "game": "Rust",
   "genre": "sandbox",
   "playlistId": "PLKtI4er_5MO7788p0SffgFvwhNbfOLTM1",
   "thumbnailUrl": "https://i.ytimg.com/vi/oc1yGg71DhY/mqdefault.jpg",
   "videoCount": 3,
   "addedDate": "2026-09-19",
   "updatedDate": "2025-02-15"
  },
  {
   "id": "gap814",
   "title": "第二回ストリーマーRUST",
   "streamer": "イブラヒム",
   "game": "Rust",
   "genre": "sandbox",
   "playlistId": "PLKtI4er_5MO4ucO8mzKgQ7-uPvANnfNz6",
   "thumbnailUrl": "https://i.ytimg.com/vi/87Q--pCtAe4/mqdefault.jpg",
   "videoCount": 3,
   "addedDate": "2026-09-19",
   "updatedDate": "2025-02-15"
  },
  {
   "id": "gap816",
   "title": "DQM3:QED並走",
   "streamer": "イブラヒム",
   "game": "DQM3",
   "genre": "rpg",
   "playlistId": "PLKtI4er_5MO5yrqt8guUHk_uIkBXRBR8z",
   "thumbnailUrl": "https://i.ytimg.com/vi/e5gSuSYac6w/mqdefault.jpg",
   "videoCount": 10,
   "addedDate": "2026-09-19",
   "updatedDate": "2025-02-14"
  },
  {
   "id": "gap802",
   "title": "ゼルダの伝説 ~裸ブレワイ~",
   "streamer": "榊ネス",
   "game": "ゼルダの伝説 ブレス オブ ザ ワイルド",
   "genre": "action",
   "playlistId": "PLE8B3Zkgr_v8vC8lw2zInDpVgEStFAdGY",
   "thumbnailUrl": "https://i.ytimg.com/vi/WFQjWe9-AuI/mqdefault.jpg",
   "videoCount": 9,
   "addedDate": "2026-09-19",
   "updatedDate": "2024-10-20"
  },
  {
   "id": "gap789",
   "title": "凛LIVE --- 迷宮校舎",
   "streamer": "静凛",
   "game": "迷宮校舎",
   "genre": "horror",
   "playlistId": "PL0EE7SG9o_r_5b-BhzwZCiIdgDNaQn7Kz",
   "thumbnailUrl": "https://i.ytimg.com/vi/0LQzmAQReiY/mqdefault.jpg",
   "videoCount": 5,
   "addedDate": "2026-09-19",
   "updatedDate": "2024-09-29"
  },
  {
   "id": "gap801",
   "title": "ゼノブレイドクロス",
   "streamer": "五十嵐梨花",
   "game": "ゼノブレイド",
   "genre": "rpg",
   "playlistId": "PL32352VPrExvn-6IrvQ3yQwhaoYuG88oX",
   "thumbnailUrl": "https://i.ytimg.com/vi/rFyGHWDmiGk/mqdefault.jpg",
   "videoCount": 6,
   "addedDate": "2026-09-19",
   "updatedDate": "2024-09-26"
  },
  {
   "id": "gap809",
   "title": "〖 完結 〗 🌠星のカービィ　夢の泉の物語",
   "streamer": "矢車りね",
   "game": "星のカービィ 夢の泉の物語",
   "genre": "action",
   "playlistId": "PLvjSd01nf3a2OK3fWVgGVbkPGXlpIAOoW",
   "thumbnailUrl": "https://i.ytimg.com/vi/RxP9CiYGHq4/mqdefault.jpg",
   "videoCount": 3,
   "addedDate": "2026-09-19",
   "updatedDate": "2024-07-30"
  },
  {
   "id": "gap806",
   "title": "🎮MGS/METAL GEAR SOLID ですわ～✨",
   "streamer": "壱百満天原サロメ",
   "game": "メタルギアソリッド",
   "genre": "action",
   "playlistId": "PLXgvhpxzP8HRJNutUoKKi5TRew577ZScq",
   "thumbnailUrl": "https://i.ytimg.com/vi/U-YKqJ2ZdUU/mqdefault.jpg",
   "videoCount": 6,
   "addedDate": "2026-09-19",
   "updatedDate": "2023-12-29"
  },
  {
   "id": "gap796",
   "title": "【完結】DARK SOULSⅢ",
   "streamer": "叶",
   "game": "DARK SOULS III",
   "genre": "action",
   "playlistId": "PLXKMRoeWMiAk2HBDZZcZfY8AeWMjxfDvn",
   "thumbnailUrl": "https://i.ytimg.com/vi/ptcL-AuXLdA/mqdefault.jpg",
   "videoCount": 8,
   "addedDate": "2026-09-19",
   "updatedDate": "2023-08-23"
  },
  {
   "id": "gap798",
   "title": "ゼルダの伝説 TOTK",
   "streamer": "叶",
   "game": "ゼルダの伝説 ティアーズ オブ ザ キングダム",
   "genre": "action",
   "playlistId": "PLXKMRoeWMiAlikTkwC7oyjd5k5GYAABRo",
   "thumbnailUrl": "https://i.ytimg.com/vi/drBjMdah26s/mqdefault.jpg",
   "videoCount": 10,
   "addedDate": "2026-09-19",
   "updatedDate": "2023-08-23"
  },
  {
   "id": "gap795",
   "title": "【メンタル回復後進行】Five Nights at Freddy's: Security Breach",
   "streamer": "夜見れな",
   "game": "Five Nights at Freddy's",
   "genre": "horror",
   "playlistId": "PLOq7ZLlTsTczsaRprfcZfjknNL6I4uwez",
   "thumbnailUrl": "https://i.ytimg.com/vi/vmrkID2e5Ao/mqdefault.jpg",
   "videoCount": 3,
   "addedDate": "2026-09-19",
   "updatedDate": "2022-10-09"
  },
  {
   "id": "gap790",
   "title": "凛LIVE --- RUST",
   "streamer": "静凛",
   "game": "Rust",
   "genre": "sandbox",
   "playlistId": "PL0EE7SG9o_r8GuwzpBeEz1L-2_M17zG-h",
   "thumbnailUrl": "https://i.ytimg.com/vi/r69VCP1Kfs4/mqdefault.jpg",
   "videoCount": 8,
   "addedDate": "2026-09-19",
   "updatedDate": "2022-08-12"
  },
  {
   "id": "gap807",
   "title": "【モンハン】操虫棍たのちい",
   "streamer": "月ノ美兎",
   "game": "モンスターハンターライズ",
   "genre": "action",
   "playlistId": "PLnReX0Ruzg5IibT_GvnXBVzREz7QzkV5e",
   "thumbnailUrl": "https://i.ytimg.com/vi/7jJdLRVvchQ/mqdefault.jpg",
   "videoCount": 2,
   "addedDate": "2026-09-19",
   "updatedDate": "2022-02-04"
  },
  {
   "id": "gap792",
   "title": "海こんにゃくで仁王2",
   "streamer": "でびでび・でびる",
   "game": "仁王2",
   "genre": "action",
   "playlistId": "PLhk3zjfjwgmfB_kPOkhECN_Z8M25kDk8s",
   "thumbnailUrl": "https://i.ytimg.com/vi/F-yDddT5qu4/mqdefault.jpg",
   "videoCount": 10,
   "addedDate": "2026-09-19",
   "updatedDate": "2021-09-27"
  },
  {
   "id": "gap815",
   "title": "Rust シーズン1",
   "streamer": "イブラヒム",
   "game": "Rust",
   "genre": "sandbox",
   "playlistId": "PLKtI4er_5MO54S5KFU9VgUqzm-v-q0CKz",
   "thumbnailUrl": "https://i.ytimg.com/vi/43vBkr8fSt0/mqdefault.jpg",
   "videoCount": 5,
   "addedDate": "2026-09-19",
   "updatedDate": "2021-09-01"
  },
  {
   "id": "gap791",
   "title": "PIENぴえん",
   "streamer": "白上フブキ",
   "game": "PIEN",
   "genre": "horror",
   "playlistId": "PL7LdRPp7xCkNyfy-9S1BRHfXq9YLUnNa6",
   "thumbnailUrl": "https://i.ytimg.com/vi/JoPPcxnPKzg/mqdefault.jpg",
   "videoCount": 3,
   "addedDate": "2026-09-19",
   "updatedDate": "2021-06-20"
  },
  {
   "id": "gap799",
   "title": "【完結】ゼルダの伝説 BOTW",
   "streamer": "叶",
   "game": "ゼルダの伝説 ブレス オブ ザ ワイルド",
   "genre": "action",
   "playlistId": "PLXKMRoeWMiAkhVgm5OLI1jfR7TvpKNwry",
   "thumbnailUrl": "https://i.ytimg.com/vi/jSlfa5XIiI0/mqdefault.jpg",
   "videoCount": 15,
   "addedDate": "2026-09-19",
   "updatedDate": "2020-12-10"
  },
  {
   "id": "gap817",
   "title": "【完】SIREN実況",
   "streamer": "レヴィ・エリファ",
   "game": "SIREN",
   "genre": "horror",
   "playlistId": "PLOzLuGbMLuwyaWvwpMcqgFRX8b_u1nYUh",
   "thumbnailUrl": "https://i.ytimg.com/vi/JfM1Tkywj7o/mqdefault.jpg",
   "videoCount": 10,
   "addedDate": "2026-09-19",
   "updatedDate": "2020-07-12"
  },
  {
   "id": "gap794",
   "title": "♡メンへラフレシア♡",
   "streamer": "物述有栖",
   "game": "メンヘラフレシア",
   "genre": "other",
   "playlistId": "PLT4Tw6XwV72gmRxvY3bpBTukLAd7LlBAM",
   "thumbnailUrl": "https://i.ytimg.com/vi/zAfo-X-ZyM0/mqdefault.jpg",
   "videoCount": 5,
   "addedDate": "2026-09-19",
   "updatedDate": "2020-05-24"
  },
  {
   "id": "gap793",
   "title": "428～封鎖された渋谷で～",
   "streamer": "樋口楓",
   "game": "428",
   "genre": "other",
   "playlistId": "PLXVn5n2jQV_C1dF7y84xafoXEIgnzsLmf",
   "thumbnailUrl": "https://i.ytimg.com/vi/hQgDTmXHdLI/mqdefault.jpg",
   "videoCount": 7,
   "addedDate": "2026-09-19",
   "updatedDate": "2020-02-20"
  },
  {
   "id": "gap804",
   "title": "美兎のSIRENシリーズ",
   "streamer": "月ノ美兎",
   "game": "SIREN",
   "genre": "horror",
   "playlistId": "PLnReX0Ruzg5IOlGTM_0wrvgIFmLDa4iAm",
   "thumbnailUrl": "https://i.ytimg.com/vi/7AWDG_NkkJM/mqdefault.jpg",
   "videoCount": 7,
   "addedDate": "2026-09-19",
   "updatedDate": "2020-02-11"
  },
  {
   "id": "gap800",
   "title": "✧星のカービィウルトラスーパーデラックス │ 天宮こころ",
   "streamer": "天宮こころ",
   "game": "星のカービィ スーパーデラックス",
   "genre": "action",
   "playlistId": "PLf_iCnxqBv4iEdrkf2bIuFNcm5Qtyn03v",
   "thumbnailUrl": "https://i.ytimg.com/vi/wwRV6nNJvBU/mqdefault.jpg",
   "videoCount": 3,
   "addedDate": "2026-09-19",
   "updatedDate": "2019-11-09"
  },
  {
   "id": "gap803",
   "title": "ゼルダの伝説スカイソードウォード",
   "streamer": "花畑チャイカ",
   "game": "ゼルダの伝説 スカイウォードソード",
   "genre": "action",
   "playlistId": "PLDtz7RRpQ_7rqeDJ0KFyLWSA1_36Dj2wW",
   "thumbnailUrl": "https://i.ytimg.com/vi/W1ukp2a79c4/mqdefault.jpg",
   "videoCount": 1,
   "addedDate": "2026-09-19",
   "updatedDate": "2019-02-08"
  },
  {
   "id": "gap779",
   "title": "トルネコの大冒険 不思議のダンジョン ちょっとステキなリマスター: Dragon Quest Heroes: Torneko's Mystery Dungeon -Classic HD-",
   "streamer": "葉山舞鈴",
   "game": "トルネコの大冒険 不思議のダンジョン",
   "genre": "rpg",
   "playlistId": "PLAOhnf4XynUM",
   "thumbnailUrl": "https://i.ytimg.com/vi/KRWiT4VOYU0/mqdefault.jpg",
   "videoCount": 1,
   "addedDate": "2026-09-18",
   "updatedDate": "2026-09-24"
  },
  {
   "id": "gap784",
   "title": "CRAZY TAXI: WORLD TOUR",
   "streamer": "姫森ルーナ",
   "game": "CRAZY TAXI",
   "genre": "racing",
   "playlistId": "PLaxM54eIayXc",
   "thumbnailUrl": "https://i.ytimg.com/vi/r_mGCHZ7-NM/mqdefault.jpg",
   "videoCount": 1,
   "addedDate": "2026-09-18",
   "updatedDate": "2026-09-13"
  },
  {
   "id": "gap781",
   "title": "⋆⸜ 空の軌跡 the 1st ⸝⋆",
   "streamer": "山神カルタ",
   "game": "空の軌跡",
   "genre": "rpg",
   "playlistId": "PLGEeokBkTJrU",
   "thumbnailUrl": "https://i.ytimg.com/vi/OqoFsJxvjI4/mqdefault.jpg",
   "videoCount": 7,
   "addedDate": "2026-09-18",
   "updatedDate": "2026-09-02"
  },
  {
   "id": "gap780",
   "title": "【完】仁王３┊︎Nioh 3",
   "streamer": "葉山舞鈴",
   "game": "仁王3",
   "genre": "action",
   "playlistId": "PLfeoyQHLFPySLJyEkp8n3Pbnn086IAMGK",
   "thumbnailUrl": "https://i.ytimg.com/vi/SHUhFrZfoh4/mqdefault.jpg",
   "videoCount": 7,
   "addedDate": "2026-09-18",
   "updatedDate": "2026-02-10"
  },
  {
   "id": "gap777",
   "title": "【完結】🌤️空の軌跡 the 1st🌤️",
   "streamer": "ニュイ・ソシエール",
   "game": "空の軌跡",
   "genre": "rpg",
   "playlistId": "PLCkTosaqp5q3Oj68rOqRDyFJCNEbpJ1tD",
   "thumbnailUrl": "https://i.ytimg.com/vi/f5Eg3syASX0/mqdefault.jpg",
   "videoCount": 11,
   "addedDate": "2026-09-18",
   "updatedDate": "2025-10-31"
  },
  {
   "id": "gap783",
   "title": "428~封鎖された渋谷で~【完】",
   "streamer": "梢桃音",
   "game": "428",
   "genre": "other",
   "playlistId": "PLnZB0mC8umaCXK7XaBOzR6kgMSchAtP2j",
   "thumbnailUrl": "https://i.ytimg.com/vi/ewRvTOqk2es/mqdefault.jpg",
   "videoCount": 9,
   "addedDate": "2026-09-18",
   "updatedDate": "2025-06-25"
  },
  {
   "id": "gap785",
   "title": "夜勤事件",
   "streamer": "姫森ルーナ",
   "game": "夜勤事件",
   "genre": "horror",
   "playlistId": "PL6gUpTCMieF5sUAf8zV6HrbdqWBzjBoCV",
   "thumbnailUrl": "https://i.ytimg.com/vi/JGmNrCgigaw/mqdefault.jpg",
   "videoCount": 1,
   "addedDate": "2026-09-18",
   "updatedDate": "2024-10-13"
  },
  {
   "id": "gap782",
   "title": "【壺おじさん】実況",
   "streamer": "鈴原るる",
   "game": "壺おじ",
   "genre": "other",
   "playlistId": "PLWvfTqENT0rzDD-SiOCvHmf0VSL_RRd1t",
   "thumbnailUrl": "https://i.ytimg.com/vi/dvFFoDrg2nQ/mqdefault.jpg",
   "videoCount": 3,
   "addedDate": "2026-09-18",
   "updatedDate": "2021-06-01"
  },
  {
   "id": "gap778",
   "title": "【完結】🔺聖剣伝説3 トライアルズオブマナ🔺",
   "streamer": "ニュイ・ソシエール",
   "game": "聖剣伝説3",
   "genre": "rpg",
   "playlistId": "PLCkTosaqp5q25-GFDem8ziZwKXO0VlGPh",
   "thumbnailUrl": "https://i.ytimg.com/vi/IqP0d9iwkfM/mqdefault.jpg",
   "videoCount": 6,
   "addedDate": "2026-09-18",
   "updatedDate": "2020-05-01"
  },
  {
   "id": "holo-156",
   "title": "アンチャーテッドシリーズ",
   "streamer": "猫又おかゆ",
   "game": "アンチャーテッド",
   "genre": "action",
   "playlistId": "PLcBqbL2HXHMg",
   "thumbnailUrl": "https://i.ytimg.com/vi/HgS9RJNBdTM/mqdefault.jpg",
   "videoCount": 2,
   "addedDate": "2026-09-17",
   "updatedDate": "2026-09-20"
  },
  {
   "id": "niji-honmahimawar-70",
   "title": "LOST JUDGMENT：裁かれざる記憶",
   "streamer": "本間ひまわり",
   "game": "LOST JUDGMENT:裁かれざる記憶",
   "genre": "action",
   "playlistId": "PLOc2cxNftxN8",
   "thumbnailUrl": "https://i.ytimg.com/vi/Rx7JPsu7Wqc/mqdefault.jpg",
   "videoCount": 1,
   "addedDate": "2026-09-17",
   "updatedDate": "2026-09-20"
  },
  {
   "id": "niji-usamiritopow-40",
   "title": "マリオテニスフィーバー だぞ！",
   "streamer": "宇佐美リト",
   "game": "マリオテニス",
   "genre": "sports",
   "playlistId": "PLudw-v3eSCjDCOmSPdSuY6mv3C_Eo9Qqz",
   "thumbnailUrl": "https://i.ytimg.com/vi/zE1Ui4UOiYU/mqdefault.jpg",
   "videoCount": 1,
   "addedDate": "2026-09-17",
   "updatedDate": "2026-02-23"
  },
  {
   "id": "niji-usamiritopow-41",
   "title": "PEAK だぞ！",
   "streamer": "宇佐美リト",
   "game": "PEAK",
   "genre": "action",
   "playlistId": "PLudw-v3eSCjDg6qEiH6Jes_gE1XNCkLIf",
   "thumbnailUrl": "https://i.ytimg.com/vi/ucKl6NOtmpM/mqdefault.jpg",
   "videoCount": 1,
   "addedDate": "2026-09-17",
   "updatedDate": "2025-08-07"
  },
  {
   "id": "niji-usamiritopow-44",
   "title": "スマブラだぞ！",
   "streamer": "宇佐美リト",
   "game": "大乱闘スマッシュブラザーズ SPECIAL",
   "genre": "action",
   "playlistId": "PLudw-v3eSCjAtk2cGgP9M9HzaiwQwKNa4",
   "thumbnailUrl": "https://i.ytimg.com/vi/BpX9Mp5DWYc/mqdefault.jpg",
   "videoCount": 3,
   "addedDate": "2026-09-17",
   "updatedDate": "2024-06-02"
  },
  {
   "id": "niji-usamiritopow-42",
   "title": "DQM3人生縛りだぞ！",
   "streamer": "宇佐美リト",
   "game": "DQM3",
   "genre": "rpg",
   "playlistId": "PLudw-v3eSCjDLVXoaicXavCmnDC8m89_9",
   "thumbnailUrl": "https://i.ytimg.com/vi/zv-0RWrsyfg/mqdefault.jpg",
   "videoCount": 7,
   "addedDate": "2026-09-17",
   "updatedDate": "2024-02-27"
  },
  {
   "id": "niji-belmondb2434-60",
   "title": "桃太郎電鉄 〜昭和 平成 令和も定番!〜",
   "streamer": "ベルモンド・バンデラス",
   "game": "桃太郎電鉄",
   "genre": "other",
   "playlistId": "PLwpJFw_gqGL_mSjvhr2UCT8qpEU5YoFET",
   "thumbnailUrl": "https://i.ytimg.com/vi/I_fyGjonOVI/mqdefault.jpg",
   "videoCount": 6,
   "addedDate": "2026-09-17",
   "updatedDate": "2023-11-23"
  },
  {
   "id": "niji-honmahimawar-71",
   "title": "【完】魔界村ーGhosts 'n Goblinsー",
   "streamer": "本間ひまわり",
   "game": "魔界村",
   "genre": "action",
   "playlistId": "PLnxwXk_UQhopqqtyL93UL0Q1AGJwMG37z",
   "thumbnailUrl": "https://i.ytimg.com/vi/hHqge-bwxpg/mqdefault.jpg",
   "videoCount": 4,
   "addedDate": "2026-09-17",
   "updatedDate": "2023-08-09"
  }
 ]
};
